{"name": "test_add_int[5-5-101]", "status": "failed", "statusDetails": {"message": "AssertionError: 实际结果10与预期结果不一致101\nassert 10 == 101", "trace": "self = <pytest_work3_calculator2.testcode.test_demo1.TestCal object at 0x0000000003C948E0>, a = 5, b = 5, expected = 101\n\n    @pytest.mark.run(order=1)\n    @pytest.mark.parametrize([\"a\", \"b\", \"expected\"], get_datas(\"add\", \"intdatas\"))\n    def test_add_int(self, a, b, expected):\n        print(\"test_add_int\")\n        actual = self.cal.add(a, b)\n>       assert actual == expected, f\"实际结果{actual}与预期结果不一致{expected}\"\nE       AssertionError: 实际结果10与预期结果不一致101\nE       assert 10 == 101\n\ntest_demo1.py:81: AssertionError"}, "attachments": [{"name": "stdout", "source": "26417f0b-5260-4f2f-a815-6085c125248f-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "5"}, {"name": "b", "value": "5"}, {"name": "expected", "value": "101"}], "start": 1597652829363, "stop": 1597652829365, "uuid": "416356bf-c2ee-4d27-a69e-de310a15677c", "historyId": "56250a3a96ad155307cda485c749d110", "testCaseId": "de893d022951450ed0b738d63d75ff69", "fullName": "test_demo1.TestCal#test_add_int", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_demo1"}, {"name": "subSuite", "value": "TestCal"}, {"name": "host", "value": "DEEP-2020QPCAMS"}, {"name": "thread", "value": "1092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo1"}]}